name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  jaffle_shop:
    +materialized: table
    +catalog: "{{ env_var('JAFFLE_CATALOG', 'builtin') }}"
    +schema: "{{ env_var('JAFFLE_SCHEMA', 'main') }}"
    staging:
      +materialized: table
      +catalog: "{{ env_var('JAFFLE_STAGING_CATALOG', env_var('JAFFLE_CATALOG', 'builtin')) }}"
      +schema: "{{ env_var('JAFFLE_STAGING_SCHEMA', env_var('JAFFLE_SCHEMA', 'main')) }}"
    orders:
      +catalog: "{{ env_var('JAFFLE_ORDERS_CATALOG', env_var('JAFFLE_CATALOG', 'builtin')) }}"
      +schema: "{{ env_var('JAFFLE_ORDERS_SCHEMA', env_var('JAFFLE_SCHEMA', 'main')) }}"
    customers:
      +catalog: "{{ env_var('JAFFLE_CUSTOMERS_CATALOG', env_var('JAFFLE_CATALOG', 'builtin')) }}"
      +schema: "{{ env_var('JAFFLE_CUSTOMERS_SCHEMA', env_var('JAFFLE_SCHEMA', 'main')) }}"
flags:
  require_generic_test_arguments_property: true
  use_catalogs_v2: true
