name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  +static_analysis: off
  jaffle_shop:
    +materialized: table
    catalog_demo:
      iceberg_rest_catalog_demo:
        +enabled: "{{ target.name == 'iceberg_rest' }}"
      local_ducklake_catalog_demo:
        +enabled: "{{ target.name == 'ducklake_no_path' }}"
      polaris_metadata_catalog_demo:
        +enabled: "{{ target.name == 'polaris_iceberg_rest' }}"
      remote_ducklake_catalog_demo:
        +enabled: "{{ target.name == 'ducklake_md_no_path' }}"
      local_filesystem_catalog_demo:
        +enabled: "{{ target.name == 'catalog_showcase' }}"
      conference_catalog_demo:
        +enabled: "{{ target.name in ['conference_catalog_demo', 'conference_catalog_demo_horizon', 'conference_catalog_demo_full'] }}"
    staging:
      +materialized: table
flags:
  require_generic_test_arguments_property: true
  use_catalogs_v2: true
